# -*- coding: utf-8 -*-
"""Assignment-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19y8k3IUk5JJaopA0aNl7Q0FQZXbSvSl-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv("/content/data.csv",encoding='latin1')
print(data.columns)
x=data["no2"].dropna()
x = x.astype(float)
print("Total valid samples:",len(x))
r=123456
ar=0.05*(r % 7)
br = 0.3 * ((r % 5) + 1)
print("ar =", ar)
print("br =", br)
z=x+ar*np.sin(br*x)
mu=np.mean(z)
variance = np.var(z)
lam = 1/(2 * variance)
c= 1/np.sqrt(2*np.pi*variance)
print("\nEstimated paramaters:")
print("mu=",mu)
print("lambda=",lam)
print("c=",c)
plt.hist(z,bins=75,density=True)
plt.xlim(0, 150)
z_range = np.linspace(min(z), max(z), 500)
pdf = c * np.exp(-lam * (z_range - mu)**2)
plt.plot(z_range, pdf)
plt.title("Histogram of z with fitted pdf")
plt.show()